name: taskflow-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL:?VITE_API_URL is required}
    container_name: taskflow_frontend_prod
    restart: unless-stopped
    networks:
      - taskflow_external

networks:
  taskflow_external:
    external: true
    name: taskflow_network
