# Generated by Django 4.2.21 on 2026-08-25 16:11
# Editado manualmente: separado en 3 migraciones (esquema -> datos ->
# constraint) para que el backfill de datos (0003) corra sobre la tabla ya
# alterada pero SIN la unique constraint todavia. Si el backfill genera un
# duplicado, la constraint (0004) falla con la tabla ya poblada -- facil de
# diagnosticar -- en vez de a mitad del backfill.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="key",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
