# Generated by Django 4.2.21 on 2026-08-29 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_alter_workspaceinvitation_status"),
        ("projects", "0004_project_key_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("color", models.CharField(default="#64748B", max_length=7)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="projectcolumn",
            name="workspace_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_columns",
                to="projects.workspacestatus",
            ),
        ),
    ]
