# Generated by Django 4.2.21 on 2026-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_seed_workspace_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacestatus",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
