FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_ENV=prod

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements ./requirements
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY . .

RUN chmod +x /app/scripts/entrypoint.prod.sh

ENTRYPOINT ["/app/scripts/entrypoint.prod.sh"]
