# Generated by Django 4.2.21 on 2026-03-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("workspace_invitation", "Workspace invitation"),
                    ("workspace_deleted", "Workspace deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
