# Generated by Django 4.2.21 on 2026-08-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("workspace_invitation", "Workspace invitation"),
                    ("workspace_deleted", "Workspace deleted"),
                    ("ticket_assigned", "Ticket assigned"),
                    ("ticket_mentioned", "Ticket mentioned"),
                    ("ticket_commented", "Ticket commented"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="notificatio_recipie_a972ce_idx",
            ),
        ),
    ]
