# Generated by Django 4.2.21 on 2026-08-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_types_and_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("workspace_invitation", "Workspace invitation"),
                    ("workspace_deleted", "Workspace deleted"),
                    ("workspace_member_removed", "Workspace member removed"),
                    ("ticket_assigned", "Ticket assigned"),
                    ("ticket_mentioned", "Ticket mentioned"),
                    ("ticket_commented", "Ticket commented"),
                ],
                max_length=50,
            ),
        ),
    ]
