# Generated by Django 4.2.21 on 2026-08-25 16:09
# Escrita a mano (no via `makemigrations`): el constraint funcional
# (`Lower("name")`) usa la forma posicional `*expressions` de
# `UniqueConstraint`, no `fields=[...]` -- ver comentario en
# apps/labels/models.py.

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("project"),
                django.db.models.functions.text.Lower("name"),
                name="unique_label_name_per_project",
            ),
        ),
    ]
