# Generated by Django 4.2.21 on 2026-08-28 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0009_ticket_number_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("relates_to", "Relates to"),
                            ("duplicate_of", "Duplicate of"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ticket_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "to_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_ticket"], name="relations_t_from_ti_740c07_idx"
                    ),
                    models.Index(
                        fields=["to_ticket"], name="relations_t_to_tick_c2c7d3_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ticketrelation",
            constraint=models.UniqueConstraint(
                fields=("from_ticket", "to_ticket", "relation_type"),
                name="unique_ticket_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketrelation",
            constraint=models.CheckConstraint(
                check=models.Q(("from_ticket", models.F("to_ticket")), _negated=True),
                name="ticket_relation_not_self",
            ),
        ),
    ]
