# Generated by Django 4.2.21 on 2026-08-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_alter_workspaceinvitation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                    ("removed", "Removed"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                    ("removed", "Removed"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
