# Generated by Django 4.2.21 on 2026-08-24 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0006_ticket_assignees"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status changed"),
                            ("priority_changed", "Priority changed"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("due_date_changed", "Due date changed"),
                            ("title_changed", "Title changed"),
                            ("commented", "Commented"),
                        ],
                        max_length=32,
                    ),
                ),
                ("from_value", models.JSONField(blank=True, null=True)),
                ("to_value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "-created_at"],
                        name="activities__ticket__c2e237_idx",
                    )
                ],
            },
        ),
    ]
