# Generated by Django 4.2.21 on 2026-08-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("due_date_changed", "Due date changed"),
                    ("title_changed", "Title changed"),
                    ("commented", "Commented"),
                    ("sprint_changed", "Sprint changed"),
                ],
                max_length=32,
            ),
        ),
    ]
