# Generated by Django 4.2.21 on 2026-04-01 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0005_ticketvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tickets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
