# Generated by Django 4.2.21 on 2026-08-25 16:13
# Editado manualmente: la UniqueConstraint del modelo se separa en la
# migracion 0009 (despues del backfill de datos en 0008), mismo patron que
# apps/projects/migrations/0002-0004 para 'Project.key'. Esquema puro aca:
# 3 campos nullable/M2M, cero riesgo para filas existentes.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0001_initial"),
        ("labels", "0001_initial"),
        ("tickets", "0006_ticket_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="labels.label"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="sprints.sprint",
            ),
        ),
    ]
