# Generated by Django 4.2.21 on 2026-08-25 16:13
# Editado manualmente:
# - La UniqueConstraint del modelo se separa en la migracion 0009 (despues
#   del backfill de datos en 0008), mismo patron que
#   apps/projects/migrations/0002-0004 para 'Project.key'.
# - `CreateModel(TicketNumberSequence)` se movio aca a mano (Django lo
#   genero en una migracion 0010 aparte porque se agrego el modelo
#   despues del primer `makemigrations`). Vive en el mismo archivo de
#   esquema que el resto de los campos nuevos de Ticket porque es
#   igual de esquema-puro (tabla nueva, sin RunPython) y conceptualmente
#   pertenece al mismo cambio: el soporte de `Ticket.number`.
# Esquema puro en todo este archivo: 3 campos nullable/M2M + 1 tabla
# nueva, cero riesgo para filas existentes.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0001_initial"),
        ("labels", "0001_initial"),
        ("projects", "0004_project_key_constraint"),
        ("tickets", "0006_ticket_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="labels.label"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="sprints.sprint",
            ),
        ),
        migrations.CreateModel(
            name="TicketNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_number_sequence",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
