# Generated by Django 4.2.21 on 2026-08-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_ticket_number_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="description_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
